### ISSUE TITLE
Booting linux on FPGA

### ISSUE THREAD

**Issue by Chiwawachiwawa** [mathis-s/SoomRV#29]
Hello sir,I fineshed the simulation of booting Linux for a while,and I want to learn more about this project,that's why I want to load it on Xilinx FPGAs to verify this project ,I'd like to how many file should I pull in design sources,(my board is Arty a7 100T),thanks a lot.

**Comment by mathis-s** [comment]
You're in luck, I'm using an Arty 100T too. I have run SoomRV on the Arty before, but that required reducing parameters (like buffer sizes) quite significantly. As such, it wasn't very fast...
That's why I'm now optimizing some parts of SoomRV for FPGAs. For example, right now I'm adapting the branch predictor to work with Block RAM. 
In 1-2 weeks, once all of that is done, I'll publish a new repo for SoomRV on Arty 100T. I'll let you know!

**Comment by Chiwawachiwawa** [comment]
> You're in luck, I'm using an Arty 100T too. I have run SoomRV on the Arty before, but that required reducing parameters (like buffer sizes) quite significantly. As such, it wasn't very fast... That's why I'm now optimizing some parts of SoomRV for FPGAs. For example, right now I'm adapting the branch predictor to work with Block RAM. In 1-2 weeks, once all of that is done, I'll publish a new repo for SoomRV on Arty 100T. I'll let you know!

That's great!thank you!!

**Comment by mathis-s** [comment]
Sorry for the delay! I just pushed the Vivado project at [SoomRV-Arty](https://github.com/mathis-s/SoomRV-Arty) You just have to flash the included image (as described in the README) to run SoomRV on the Arty. Let me know how it goes!

**Comment by Chiwawachiwawa** [comment]
> Sorry for the delay! I just pushed the Vivado project at [SoomRV-Arty](https://github.com/mathis-s/SoomRV-Arty) You just have to flash the included image (as described in the README) to run SoomRV on the Arty. Let me know how it goes!

Thank you !! I'll try it!
