### ISSUE TITLE
how to use anthor march to run drhy.s

### ISSUE THREAD

**Issue by Eric9908** [mathis-s/SoomRV#34]
Sorry to bother you, but I would like to until how the dhrt_1.s in test_program is generated? Is it generated by riscv32-unknown-linux-gnu-gcc -march=rv32imac_zba_zbb -O3 -finline-limit=128 -S dhry_1.c -o dhry_1.s -lc -lm? I'd like to see how the processor behaves with dhrystone under -march=rv32imac_zicsr.
I tried compiling riscv32-unknown-linux-gnu-gcc -march=rv32imac_zicsr -O3 -finline-limit=128 -S dhry_1.c -o dhry_2.s -lc -lm but found that the VTop doesn't run the dhry_1.s correctly.I used the the 13.2 version of risc-v gcc.
Here's a picture of what gets stuck when I run it.
![微信图片_20240415110101](https://github.com/mathis-s/SoomRV/assets/96467078/06d11e44-a3ef-42eb-be25-1769edac59ba)

**Comment by Eric9908** [comment]
I still have a question, how to use konata to display the pipeline? I need to use gem5 to execute './build/RISCV/gem5.opt --debug-flags=O3PipeView --debug-file=trace.out configs/example/se.py --cpu-type=O3CPU --caches -- cmd /home/test'? Among them, ‘/home/test’ is the result of executing ‘riscv32-linux-gnu-gcc test.c -o test’. But my question is how to simulate the pipeline process of executing the test on the written risc-v processor?

**Comment by mathis-s** [comment]
To compile dhrystone, you can use `riscv32-unknown-linux-gnu-gcc -march=rv32imac_zicsr -mstrict-align -mabi=ilp32 -DTIME -S -O1 -falign-loops  test_programs/dhry_1.c -o test_programs/dhry_1.s` (no need to link anything as we're just compiling to assembly).

When you run `./obj_dir/VTop test_programs/dhry_1.s`, the testbench will then link the executable to `entry.o`. This might be problematic for benchmarking because `strcmp` is implemented in `entry.o` and also makes use of bitmanip instructions. You may want to replace the `strcmp` implementation in `entry.s` and then run something like `riscv32-unknown-elf-as -mabi=ilp32 -march=rv32imac_zicsr_zba_zbb test_programs/entry.s -o test_programs/entry.o` to re-make `entry.o`.

**Comment by mathis-s** [comment]
For visualization with Konata, first uncomment `#define KONATA` in `Top_tb.cpp`. If you then run VTop as usual, it will create a `trace_konata.txt` file which you can open with Konata.

**Comment by Eric9908** [comment]
I want to know what's the rationale behind generating konata files?
Another question is: since I don't use B extension, how can I replace the orc instructions of strcpy and strcmp in entry.s？
`$ riscv32-unknown-linux-gnu-as -mabi=ilp32 -march=rv32imac_zicsr entry.s -o entry.o

entry.s: Assembler messages:

entry.s:164: Error: unrecognized opcode `orc.b t1,t0', extension `zbb' required

entry.s:190: Error: unrecognized opcode `orc.b t0,t0', extension `zbb' required`

**Comment by mathis-s** [comment]
Sorry for the delay! A simple solution would be to just remove all strcmp code from entry.s and instead paste some strcmp implementation in C into dhry_1.c.

Konata files are just what's required by Konata to visualize traces, I'm not sure what you mean by rationale.

**Comment by Eric9908** [comment]
Thank you for your answers and patience firstly！
I tried to avoid using B extension for both strcpy and strcmp in entry.s and it worked.
I am looking for another method and want to add in dhry_1.c:
```
//extern int strcmp(const char* l, const char* r);
int strcmp(const char *s1, const char *s2) {
     while (*s1 && *s2 && *s1 == *s2) {
         s1++;
         s2++;
     }
     return *s1 - *s2;
}
```
```
//extern char* strcpy(char *restrict d, const char *restrict s);
char* strcpy(char *restrict d, const char *restrict s)
{
for (; (*d=*s); s++, d++);
return d;
};
```
Execute `riscv32-unknown-linux-gnu-gcc -march=rv32imac_zicsr -mstrict-align -mabi=ilp32 -DTIME -S -O1 -falign-loops new_dhry_1.c -o new_dhry_1.s`
Comment out the global definitions of strcmp and strcpy in entry.s, and then execute `riscv32-unknown-linux-gnu-as -mabi=ilp32 -march=rv32imac_zicsr test_programs/entry.s -o test_programs/entry.o`;
I still failed and couldn't run `./obj_dir/VTop test_programs/new_dhry_1.s`
Appear
riscv32-unknown-linux-gnu-ld: warning: section `.data' type changed to PROGBITS
ob[8][7]: ][7]: ob[8][7]: Int_Comp: ob[8][7]: Next_Ptr_Glob->ob[8][7]: SOME STRING

Another idea I had was to include <stdio.h>, no longer write strcmp, strcpy, printf functions, etc., and then compile jointly, but I also failed.
I'm confused why dhrystone can be so high. Is it because of strcmp and strcpy?

**Comment by mathis-s** [comment]
I'm not quite sure what error you're getting here. Unfortunately you can't just use `<string.h>` implementations because we're running bare-metal code, there's no stdlib.

To answer your question regarding the high dhrystone score: Yes, the strcmp absolutely has a big impact on it. SoomRV's branch predictor also seems to work really well with dhrystone, a lot better than e.g. in Coremark. `dhry_1.s` is also built with a lot of optimizations (O3 and inlining). If you downgrade to O1 you get around ~4.6 DMIPS/MHz.

I generally wouldn't take Dhrystone scores too seriously though. There's just too many variables at play... Coremark is a bit better in this regard

**Comment by Eric9908** [comment]
I know that dhrystone is affected by compiler optimization, but I didn't expect it to have such a significant impact on benchmark results.The coremark scores I measured are much more normalized.Thanks again for your patience!
